export { default as HeroSection } from './sections/HeroSection'
export { default as TrustSection } from './sections/TrustSection'
export { default as CapabilitiesSection } from './sections/CapabilitiesSection'
export { default as StatsSection } from './sections/StatsSection'
export { default as CTASection } from './sections/CTASection'
